Tile information implementation
R7G3/TinyTBS pull request #25
Opened 2023-02-26 19:57 UTC by LizardWi-zard

Добавление информации о клетках с обновлением в реальном времени

2023-02-26 20:37 UTC, PoisonousJohn requested changes

2023-02-26 20:37 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Controllers/TileInfoController.cs
> +    [SerializeField] private RectTransform _list;
Тут лист -- это заделка на будущее?

2023-02-26 20:37 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +    private string _unitFraction;
Вот это все не нужно. Можно же просто локальными переменными заменить там, где это нужно. Сейчас это выглядит как куча неиспользуемого кода.

2023-02-26 20:37 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +public class TileInformation : MonoBehaviour
В целом, этот класс не нужно наследовать от MonoBehavior, он же не является компонентом?

Этот класс можно сделать статическим с одним статическим методом

2023-02-26 20:37 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Controllers/TileInfoController.cs
> +    }
Метод должен отражать то что он делает. Т.е. в данном случае лучше назвать SetTileInfo, например.

2023-02-26 20:37 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Controllers/TileInfoController.cs
> +    [SerializeField] private TextMeshProUGUI _title;
Аналогичный вопрос к _title, по факту же это _tileInfo

2023-02-26 20:37 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +        string text = $"Terrain: {_tileType} \nDefence bonus: {_tileDefence}";
вот смотри, по факту здесь используется всего две переменных, зачем сохранять все что написано выше?

2023-02-26 21:44 UTC, LizardWi-zard commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +        string text = $"Terrain: {_tileType} \nDefence bonus: {_tileDefence}";
Оставил для проверки на работоспособность. Хотел посоветоваться как лучше сделать, чтоб всю полученную информацию отобразить в лучшем виде. Там много переменных, данные которых нужно отобразить

2023-02-26 21:46 UTC, LizardWi-zard commented on Tiny TBS/Assets/Scripts/Controllers/TileInfoController.cs
> +    [SerializeField] private RectTransform _list;
Делал по примеру из другого префаба. Уберу, но если надо убрать полностью или использовать, то оставлю на твоё усмотрение

2023-02-26 21:47 UTC, LizardWi-zard commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +public class TileInformation : MonoBehaviour
Не понимаю как лучше сделать статическим классом со статическим методом

2023-02-27 08:27 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +        string text = $"Terrain: {_tileType} \nDefence bonus: {_tileDefence}";
Информация делится на разные виджеты, поэтому логично завести enum, где описать виды виджетов, и передать его как параметр в метод.

`string GetTileInfo(Vector3 position, InfoType infoType)`

Внутри этого метода, сделать switch по infoType и вернуть соответствующую этому типу информацию

2023-02-27 08:29 UTC, PoisonousJohn commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +public class TileInformation : MonoBehaviour
1. Убираешь наследование от MonoBehavior
2. делаешь класс статическим `public static class`
3. Убираешь все свойства
4. Делаешь метод статическим `public static string GetTileInfo(...)`
5. Вовне вызываешь метод как `TileInformation.GetTileInfo(...)`

Так как класс статический -- не нужно создавать с ним объект.
Объект нужен только тогда, когда у объект есть состояние, которые нужно хранить между вызовами методов. Здесь, фактически оно не нужно

2023-02-27 09:54 UTC, LizardWi-zard commented on Tiny TBS/Assets/Scripts/Tiles/TileIformation.cs
> +        string text = $"Terrain: {_tileType} \nDefence bonus: {_tileDefence}";
Сделал разделение через switch. Для отображения в проекте показываю только информацию про отдельную клетку

2023-02-27 19:10 UTC, merged